[package]
name = "mudhuts"
edition.workspace = true
version.workspace = true

[dependencies]
mudhuts-term = { path = "../mudhuts-term" }
mudhuts-protocols = { path = "../mudhuts-protocols", features = ["server"] }
alacritty_terminal = "0.26"
serde = { version = "1", features = ["derive"] }
toml = "1"
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-journald = "0.3"
smithay-drm-extras = { git = "https://github.com/Smithay/smithay.git", rev = "4cf0b62028039661477d482ec4758b687d8f4392", default-features = false }

[dependencies.smithay]
workspace = true
features = [
    "backend_winit",
    "wayland_frontend",
    "desktop",
    "backend_session_libseat",
    "backend_udev",
    "backend_drm",
    "backend_gbm",
    "backend_libinput",
]
